136-fix-renamed Add Maintenance to Update Maintenance
mikaelacaron/Basic-Car-Maintenance pull request #149
Opened 2023-10-11 06:16 UTC by AakifNadeem

# What it Does
* Closes #136 
* Describe what your change does
Update Add Maintenance to Update Maintenance
Renamed Localizations as well.

# How I Tested
* Add a list of steps to show the functionality of your feature
For example:
* Run the application
* Tap the (+) button
* See this screen
etc...

# Notes
* Anything else that should be noted about how you implemented this feature?

# Screenshot
* Add a screenshot of your new feature! OR show a screen recording of it in action. (On the simulator press Cmd + R to record, and the stop button when done). **This video should be no longer than 30 seconds.**

2023-10-11 13:07 UTC, mikaelacaron commented
@AakifNadeem do you know the languages you translated the new string to? If not, I'd prefer you leaving them empty and someone else can make a new PR updating the translations

2023-10-11 13:24 UTC, AakifNadeem commented
> @AakifNadeem do you know the languages you translated the new string to? If not, I'd prefer you leaving them empty and someone else can make a new PR updating the translations

Its just quick google translation.

2023-10-11 17:13 UTC, mikaelacaron commented
@AakifNadeem can you remove those then, I'd rather have real people making these translation for Hacktoberfest right now, thank you!

2023-10-11 17:27 UTC, mikaelacaron requested changes
Also be sure to fix this change, so that this isn't deleted in the xcscheme thanks!

2023-10-11 18:18 UTC, AakifNadeem commented
@mikaelacaron I've removed the localization kindly check.

2023-10-12 01:24 UTC, mikaelacaron requested changes
The wrong view was changed! See comment thanks. Also after you fix this, please click the re-review button, so I'm notified to take a look again
<img width="345" alt="Re-review button" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/95fe7a6b-56de-45ab-af73-737182c4c1d0">

2023-10-12 01:24 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/xcshareddata/xcschemes/Basic-Car-Maintenance-WidgetExtension.xcscheme
>        debugDocumentVersioning = "YES"
Also please put back this line

2023-10-12 10:20 UTC, closed without merging