Connect Vehicles and Maintenance Events
mikaelacaron/Basic-Car-Maintenance pull request #163
Opened 2023-10-12 14:37 UTC by hanhqvu

# What it Does
* Closes #141
* This PR will add a Picker (pop-up) menu to `AddMaintenanceView `& `EditMaintenanceView`

# How I Tested
* I added sample vehicles data to show in the preview

# Notes
* There is no validation upon adding/editing to ensure a vehicle has been selected

# Screenshot
<img width="266" alt="Screenshot 2023-10-12 at 23 36 14" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/82783173/f412266b-8bb4-4006-b73c-6bbf95f0433f">

2023-10-13 03:02 UTC, mikaelacaron requested changes
It's almost there! In the `AddMaintenanceView` and the `EditEventDetailView` it's not keeping track when you select a vehicle in the list, the row isn't changing.

Also can you show which vehicle is selected, in the `DashboardView`

2023-10-13 03:02 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Dashboard/Views/AddMaintenanceView.swift
> +
This isn't keeping track of the vehicle that's selected. See video

https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/c3da09b6-762f-409b-8a5b-dc43765b2d2b

2023-10-13 14:24 UTC, hanhqvu commented
> It's almost there! In the `AddMaintenanceView` and the `EditEventDetailView` it's not keeping track when you select a vehicle in the list, the row isn't changing.
> 
> Also can you show which vehicle is selected, in the `DashboardView`

![image](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/82783173/2527c447-c75f-46bf-bfb0-5618a358eeca)

Regarding showing which vehicle is selected, do you mean like in the picture?

2023-10-14 03:25 UTC, mikaelacaron commented
> Regarding showing which vehicle is selected, do you mean like in the picture?

Yes just show the name, and it's fine to just add it into the `VStack` that's already there (it can be a separate issue for someone to style it better)

2023-10-14 03:26 UTC, mikaelacaron commented
Also be sure to merge the `dev` branch into your branch (and resolve the merge conflicts)

2023-10-14 15:48 UTC, hanhqvu commented
@mikaelacaron I added the fix for the picker menu & added the vehicle info to the Dashboard view

2023-10-15 01:36 UTC, mikaelacaron approved these changes
I added two changes to `EditEventDetailView` and `AddMaintenanceView` where to use an optional rather than an empty `selectedVehicle` object

2023-10-15 01:36 UTC, merged

2023-10-15 02:11 UTC, hanhqvu commented
@mikaelacaron Thank you for the changes. I added #174 so someone can style `DashboardView` better!