85-Interactive-Tutorial
mikaelacaron/Basic-Car-Maintenance pull request #184
Opened 2023-10-17 19:41 UTC by ampsonic

# What it Does
* Closes #85 
* Creates an interactive tutorial for how to get started

# Notes
* In order to view the documentation, in Xcode select Product>Build Documentation

# Screenshot
![CleanShot 2023-10-17 at 12 40 33@2x](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/25410020/53d941c8-2717-49dc-8f4b-6d595f13d820)

2023-10-17 19:44 UTC, mikaelacaron commented
I haven't looked at this yet, but can you make dark screenshots too for GitHub? @ampsonic

2023-10-17 22:59 UTC, ampsonic commented
> I haven't looked at this yet, but can you make dark screenshots too for GitHub? @ampsonic

You would like the screenshots inside the tutorial to be in dark mode, is that correct?

2023-10-17 23:04 UTC, mikaelacaron commented
Almost! You can have light _and_ dark mode screenshots! DocC figures out which one to use depending on your computer settings

This [WWDC video](https://developer.apple.com/wwdc23/10244) shows you how

2023-10-18 02:19 UTC, mikaelacaron requested changes
Great work!! A couple of questions on some of the formatting.

Also with Terminal, can you install `https://ohmyz.sh/` onto your machine? The default theme will change the look of your terminal so that it doesn't have your name in all of the terminal screenshots, and instead would look something like this

<img width="937" alt="Screenshot 2023-10-17 at 10 18 26 PM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/497f512b-ce25-4f24-bc6e-00b02a28c640">

If you have a question on these changes, you can comment on the thread, otherwise if you don't have any questions, click resolve, and you've addressed everything please click the re-review button
<img width="345" alt="Re-review button" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/51187c07-6e47-4937-8f15-12029db0a19e">

2023-10-18 02:19 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +    @Intro(title: "How to contribute to this project.") {
Capitalize this title please

2023-10-18 02:19 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +            @Step {
Can you add a link to this?

2023-10-18 02:19 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +        @ContentAndMedia {
Can you edit the description to: "Configuring the project with the xcconfig files to build the project on your machine"

2023-10-18 02:19 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +            BEFORE starting on an issue, comment on the issue you want to work on.
can you make the work before also bold?

2023-10-18 02:19 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +                Checkout a new branch (from the dev branch) to work on an issue. The feature-name part of the branch can be shortened or omitted and you add your username instead. No commits should b
The first sentence I'd put in the "step" the rest of it, I'd add as a "note"

2023-10-18 02:19 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +                git checkout -b issueNumber-feature-name
Is it possible to make all the commands "formatted as code?" as opposed to it just looking like text?

2023-10-23 02:17 UTC, mikaelacaron commented
@ampsonic actually don't worry about the light / dark mode right now, I'll add that as an issue to do later

Can you fix the other comments, and then I'll be able to merge this!

2023-10-23 16:06 UTC, ampsonic commented
> @ampsonic actually don't worry about the light / dark mode right now, I'll add that as an issue to do later
> 
> Can you fix the other comments, and then I'll be able to merge this!

Sounds good, on it!

2023-10-23 18:15 UTC, mikaelacaron commented
@ampsonic One thing though, can you please still change the terminal stuff (like I mentioned with ohmyz.sh) and on the images, they show your profile picture, can you hide that with a circle on top of it, so it's not confusing to others?

Otherwise another thing, if you want, I can make these screenshots for you, and you add them into the project. Let me know which

2023-10-23 18:26 UTC, ampsonic commented
> @ampsonic One thing though, can you please still change the terminal stuff (like I mentioned with ohmyz.sh) and on the images, they show your profile picture, can you hide that with a circle on top of it, so it's not confusing to others?
> 
> Otherwise another thing, if you want, I can make these screenshots for you, and you add them into the project. Let me know which

I think I already have the screenshots updated with OhMyZSH, unless I made a mistake when I pushed.   But I can add a circle to the GH screenshots.

2023-10-23 19:16 UTC, mikaelacaron commented
> I think I already have the screenshots updated with OhMyZSH

I'll take a look later! I haven't checked back yet, but I wanted to note those I did want to change, colors are fine, I'll make a task to update them later

Thanks for updating this!

2023-10-23 19:35 UTC, ampsonic commented
> > I think I already have the screenshots updated with OhMyZSH
> 
> I'll take a look later! I haven't checked back yet, but I wanted to note those I did want to change, colors are fine, I'll make a task to update them later
> 
> Thanks for updating this!

Committed the updated GitHub screenshots with my avatar replaced.

2023-10-24 04:16 UTC, mikaelacaron approved these changes
Great work!! Thanks for making those changes, I made small edits related to formatting and some phrasing

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/Tutorial Table of Contents.tutorial
> +        How to get started contributing to this project.
```suggestion
        How to get started contributing to this project
```

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +                Download [Xcode 15](https://developer.apple.com/xcode/resources/) or later.
```suggestion
                Download [Xcode 15.0](https://developer.apple.com/xcode/resources/) or later.
```

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +        Here you will find instructions on how to prepare, fork, clone, configure, build and contribute to this project.
```suggestion
        Here's instructions on how to prepare, fork, clone, configure, build and contribute to this project. This tutorial uses the [GitHub CLI](https://cli.github.com/)
```

Rephrasing, also linking that this specifically uses the GitHub CLI

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +
```suggestion
            @Step {
                Install [GitHub CLI](https://cli.github.com/) command line tools
            }

            @Step {
               Use `gh auth login` to authenticate with the [GitHub CLI](https://cli.github.com/manual/gh_auth_login)
            }
```

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +                This works with both free or paid Apple Developer accounts. Do NOT run this app on a real device due to issues with the Sign in With Apple capability.
```suggestion
                Note: A free account does not have a `DEVELOPMENT_TEAM`. Instead fill in `ABC123`. Do NOT run this app on a real device due to issues with the Sign in With Apple capability.
```

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +            This prevents two people from working on the same issue. Mikaela (the maintainer) will assign you that issue, and you can get started on it.
```suggestion
            This prevents two people from working on the same issue. [Mikaela](https://github.com/mikaelacaron) (the maintainer) will assign you that issue, and you can get started on it.
```

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +                Checkout a new branch (from the dev branch) to work on an issue.
```suggestion
                Checkout a new branch (from the `dev` branch) to work on an issue. 
```

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +                The feature-name part of the branch can be shortened or omitted and you add your username instead. No commits should be made to the main branch directly. The main branch shall only co
```suggestion
                The `feature-name` part of the branch can be shortened or omitted and you add your username instead. No commits should be made to the `main` branch directly. The `main` branch shall only consist of the deployed code. Developers are expected to work on feature branches, and upon successful development and testing, a PR (pull request) must be opened to merge with `dev`. `git checkout -b issueNumber-feature-name`
```

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +            }
```suggestion
            @Step {
                Fork the repo on GitHub to your own account.  Select Fork from the Basic-Car-Maintenance github page.
                
                This example shows a fork to `ampsonic`'s profile
                
                @Image(source: 2-fork.png, alt: "GitHub Fork")
            }
```

2023-10-24 04:16 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/getting-started.tutorial
> +    @Intro(title: "How to Contribute to this Project.") {
```suggestion
    @Intro(title: "How to Contribute to this Project") {
```

2023-10-24 04:18 UTC, merged