Adding App Store Connect texts as DocC article #124
mikaelacaron/Basic-Car-Maintenance pull request #195
Opened 2023-10-21 00:40 UTC by SuzGupta

…re listing

# What it Does
* Closes #124 
* Adds suggested name, subtitle, description, keywords and some other settings to copy and paste into App Store Connect when the maintainer is ready to submit the app

# How I Tested
* Choose Build Documentation from Xcode's Product menu
* Review the result

# Notes
* There's more that could be said about App Store Connect, but I think this is a solid start.

# Screenshot
<img width="1008" alt="AppStoreListingArticle" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/5115383/3630f9a2-f4e8-454f-a643-56ed9f3e2d96">

2023-10-21 00:41 UTC, SuzGupta commented
Blergh, that was two more commits than it needed to be, but I think the actual text is fairly solid.

2023-10-21 05:15 UTC, mikaelacaron requested changes
Love this! Thanks for being so detailed!
I have a few suggestions about also including verbiage for electric vehicles and hybrids

Once you make those changes, click "Resolve" to resolve the comment I made. If you have any questions you can comment directly on that thread.

After you're done, click the re-review button

![image](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/6a00fd1a-932e-48ce-9c1d-4affe7ac1cec)

2023-10-21 05:15 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/App Store Listing.md
> +Set up the app's name and subtitle under **General** ▸ **App Information** in the **Localizable Information** section at the top of the page. You have a maximum of 30 characters for each field. Accor
```suggestion
Set up the app's name and subtitle under **General** ▸ **App Information** in the **Localizable Information** section at the top of the page. You have a maximum of 30 characters for each field. According to [Appfigures](https://appfigures.com/resources/guides/app-name-optimization), you should portion out keywords between the name and the subtitle for optimal ASO, App Store Optimization, which is the magic of doing everything you can in your App Store listing to make it highly visible in the Store.
```

2023-10-21 05:15 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/App Store Listing.md
> +`Basic Auto Vehicle Maintenance lets you easily log repairs and routine service. You can also track odometer readings, handy for business travel or just to figure out how far your fuel gets you.`
Can we also word this in a way that accommodates electric vehicles?

2023-10-21 05:15 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/App Store Listing.md
> +Suggested: `car,van,motorcycle,bike,care,repair,manage,easy,simple,oil,change,tire,rotation,record,fuel,gas,log`
Also some kind of electric vehicles words be great!

2023-10-23 00:22 UTC, SuzGupta commented on Basic-Car-Maintenance/Documentation.docc/App Store Listing.md
> +Suggested: `car,van,motorcycle,bike,care,repair,manage,easy,simple,oil,change,tire,rotation,record,fuel,gas,log`
will remove `motorcycle` and `log` and add `electric` and `charge`, leaving us at exactly 100 character

2023-10-23 00:23 UTC, SuzGupta commented on Basic-Car-Maintenance/Documentation.docc/App Store Listing.md
> +`Basic Auto Vehicle Maintenance lets you easily log repairs and routine service. You can also track odometer readings, handy for business travel or just to figure out how far your fuel gets you.`
will change that last bit to read "how far your fuel or battery charge gets you"

2023-10-23 04:26 UTC, mikaelacaron approved these changes
Awesome!! Thanks for being so detailed! I have one small suggestion that I'll commit directly

2023-10-23 04:26 UTC, mikaelacaron commented on Basic-Car-Maintenance/Documentation.docc/App Store Listing.md
> +Here's the Apple developer site covering how to set up an app's product page, as well as the many other things you can do with App Store Connect: https://developer.apple.com/app-store-connect/
```suggestion
Here's the Apple developer site covering how to set up an app's product page, as well as the many other things you can do with App Store Connect: [https://developer.apple.com/app-store-connect/](https://developer.apple.com/app-store-connect/)
```

Makes this into a hyperlink

2023-10-23 04:27 UTC, merged