Bug-Fix issue: 182 Picker in AddMaintainanceView is not working
mikaelacaron/Basic-Car-Maintenance pull request #196
Opened 2023-10-21 03:50 UTC by rramirez-dev

Updated the vehicle picker to user the vehicle id and not the vehicle object

# What it Does
* Closes #182 
* Describe what your change does
   The fix allows the user to select a vehicle from the 
   vehicle picker in the AddMaintainanceView form that
   is not the first vehicle in the list.

# How I Tested
* Add a list of steps to show the functionality of your feature
For example:
* Run the application
* Tap the (+) button
* See this screen
etc...

1. Launch the App
2. Load the dashboard by navigating to a different tab     and then select the dashboard tab again.
3. Tap the plus sign to add a new event
4. Enter a title
5. Select a vehicle that is not the first one on the list
6. Tap Add

# Notes
* Anything else that should be noted about how you implemented this feature?
* I filtered the vehicles array based on the id of the vehicle that the user selected. I then get the first item in the array and pass it to the MaintainanceEvent view.

# Screenshot
![Simulator Screen Recording - iPhone 15 - 2023-10-20 at 21 49 41](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22773854/8014167a-decc-4823-b52a-f9daa923885f)

2023-10-21 16:45 UTC, mikaelacaron reviewed
Can you make this work using the `Vehicle` object as opposed to the id?

2023-10-23 04:33 UTC, mikaelacaron requested changes
nevermind sorry for the confusion, go ahead and use the `id`, that's how it's done in the `AddOdometerReadingView`

Also note you don't need the `vehicle as Vehicle` anymore because of that, and technically with the current way that you fixed this the `if !vehicles.isEmpty` check wouldn't be needed, because you made the `selectedVehicle` optional

2023-10-23 21:34 UTC, rramirez-dev commented
Do want me to remove the "vehicle as Vehicle" tag or do I just set the tag to "vehicle" instead of "vehicle as Vehicle"?

2023-10-24 00:51 UTC, mikaelacaron commented
> So I should remove `vehicle as Vehicle` from the tag and replace it with `vehicle.id`

Yes because it's not necessary to cast the vehicle as it's own type, the goal is to use the `id` as the main point of data for the picker, like you had it before

2023-10-24 04:30 UTC, mikaelacaron approved these changes
Good work! Just a small comment and I can merge this

2023-10-24 04:30 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Dashboard/Views/AddMaintenanceView.swift
> +                        ForEach(vehicles, id: \.self) { vehicle in
```suggestion
                        ForEach(vehicles) { vehicle in
```

This is not needed, it's about if the elements in the `ForEach` are `Identifiable`, which they are, the `id` doesn't need to be explicitly noted

2023-10-24 04:30 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Dashboard/Views/AddMaintenanceView.swift
> +                                                            vehicle: vehicle)
Going to push a change to fix the alignment of this

2023-10-24 04:33 UTC, merged