Adding Localization Support to Basic-Car-Maintenance Project
mikaelacaron/Basic-Car-Maintenance pull request #23
Opened 2023-10-01 13:14 UTC by samuelowino

Issue #22

# What it Does
* Closes issue #22
* Describe what your change does
The code adds JSON objects with keys representing different messages or labels in the application. Each key has associated localization information for various languages. This PR will add support for: 

1. French
2. Portuguese
3. Japanese
4. Mandarine
5. Arabic

# How I Tested
* Add a list of steps to show the functionality of your feature

- Install the app on iPhone or Mac
- Go to Settings on the phone
- Select General Settings
- Click on change language
- Select one of the Newly supported languages
- Go back to the app which will now render the selected language

# Notes
![Simulator Screenshot - iPhone 14 Pro - 2023-10-01 at 16 03 19](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/10231690/8e65c640-ee4e-4ef9-a9d3-a33a65612c69)

I've used the existing Localizable catalog file. I only expanded list of supported languages

# Screenshot
![Simulator Screenshot - iPhone 14 Pro - 2023-10-01 at 15 38 19](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/10231690/fa1ad8c9-4e35-4f8a-98c6-36ab3da06401)
![Simulator Screenshot - iPhone 14 Pro - 2023-10-01 at 15 38 23](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/10231690/516764c5-94ae-44c0-971e-92fa3cddd2e8)

2023-10-01 19:30 UTC, mikaelacaron commented
@samuelowino Thanks for contributing! Do you know all these languages? I'm curious! Can you instead please only contribute 2 additional languages, to allow others to be able to contribute as well.
Also note that this is actually covered with issue #7 and I closed #22 because of duplication

2023-10-02 08:42 UTC, samuelowino commented
> @samuelowino Thanks for contributing! Do you know all these languages? I'm curious! Can you instead please only contribute 2 additional languages, to allow others to be able to contribute as well.
> Also note that this is actually covered with issue #7 and I closed #22 because of duplication

Hey @mikaelacaron, thanks for reviewing the code. I am happy to make the changes

2023-10-02 19:09 UTC, mikaelacaron requested changes
Make those changes, and then click the re-review button, thanks!

<img width="345" alt="Re-review button" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/c7772ae8-e7a3-40af-9f7a-3833d35751ec">

2023-10-06 17:03 UTC, mikaelacaron commented
Closing this PR for now, as noted above

2023-10-06 17:03 UTC, closed without merging