174 fix eventlist design
mikaelacaron/Basic-Car-Maintenance pull request #254
Opened 2023-10-30 19:14 UTC by mitaligondaliya

# What it Does
* Closes #issueNumber
* Closes https://github.com/mikaelacaron/Basic-Car-Maintenance/issues/174
* Changed the date style as .short

# How I Tested

For example:
* Run the application
* Dashboard view Tap the (+) button
* See the dashboard event list

# Screenshot
![Simulator Screenshot - iPhone 15 Plus - 2023-10-31 at 00 29 04](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/29226517/947aef93-0379-4ba9-8068-9507f6a58c0a)

2023-10-30 19:17 UTC, mitaligondaliya commented
@mikaelacaron  You were saying to add the event formatter inside the body? I tried but inside the body we can't assign the dates style So, I kept it as private computed property there.

2023-10-31 02:53 UTC, mikaelacaron commented
> @mikaelacaron You were saying to add the event formatter inside the body? I tried but inside the body we can't assign the dates style So, I kept it as private computed property there.

No I mean like this way, from [this article](https://www.hackingwithswift.com/quick-start/swiftui/how-to-format-text-inside-text-views), sorry my other comment looks like I never linked it properly

You put the `formatter` parameter inside the string interpolation, as opposed to using the `string` function that's on the formatter like you did here:

`eventDateFormatter.string(from: event.date)`

2023-10-31 03:01 UTC, mikaelacaron requested changes
Note the comment I already left about the date formatter, also, the swipe action on the `DashboardView`, the word `Edit` disappeared?

If you have any questions, you can comment directly on that thread, otherwise click the resolve button once you've addressed my comment. Once you fix everything, please click the re-review button

<img width="345" alt="Re-review button" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/c4ee2926-f8c0-4b0d-9d4a-55f90ca886be">

2023-10-31 03:01 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/xcshareddata/xcschemes/Basic-Car-Maintenance-WidgetExtension.xcscheme
> -      askForAppToLaunch = "Yes"
This shouldn't be removed

2023-10-31 03:01 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Dashboard/Views/DashboardView.swift
> +                            .foregroundStyle(.primary)
what color is `.primary`? What does changing this do, vs the default?

2023-10-31 04:51 UTC, mitaligondaliya commented on Basic-Car-Maintenance/Shared/Dashboard/Views/DashboardView.swift
> +                            .foregroundStyle(.primary)
That is default colour, black and white depending on the device mode dark and light.

2023-10-31 05:22 UTC, mitaligondaliya commented
<img width="410" alt="Screenshot 2023-10-31 at 10 37 46 AM" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/29226517/9c93188c-c2ae-4368-845f-9e8bf72c5498">

Swipe action Edit word is there not disappeared.

2023-10-31 05:25 UTC, mitaligondaliya commented
@mikaelacaron I've pushed the changes please review it and let me know if there is anything need to change.

2023-11-01 02:50 UTC, mikaelacaron approved these changes
Great work!! Thanks for making those changes, haha I found the issue for the edit button disappearing for me on a swipe action (lol I'll make this a separate issue)

2023-11-01 02:50 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Dashboard/Views/DashboardView.swift
> +        }()
The indentation is off, the body of the computed property is indented too far, and the ending brace `}` should be even with the word `private`
I'll fix this manually, don't worry about it

2023-11-01 02:50 UTC, merged

2023-11-06 10:38 UTC, mitaligondaliya commented
@mikaelacaron This one is showing not accepted in hacktoberfest, Could you please mark it as `hacktoberfest-accepted`?

2023-11-06 15:11 UTC, mikaelacaron commented
It was merged so it should show as accepted, sometimes it takes a minute, but I did mark it as that too

2023-11-06 16:27 UTC, mitaligondaliya commented
> It was merged so it should show as accepted, sometimes it takes a minute, but I did mark it as that too

Okay Thanks 👍🏼 @mikaelacaron