Firebase Local Emulator
mikaelacaron/Basic-Car-Maintenance pull request #256
Opened 2023-10-31 18:12 UTC by n0rthk1n9

# What it Does
* Closes #14
* It makes the app testable against a local emulated Firebase Auth and Firebase Firestore instance

# How I Tested
* Make sure Node v 8.0 or higher is installed
* Make sure Openjdk v 11 or higher is installed (If you installed it via brew, don't forget to add the executable to $PATH, brew will output it as a handy command to execute for you)
* Make sure firebase-cli is installed (`npm install -g firebase-tools`)
* Make sure you ran  `firebase login` and authenticated successfully
* Go to `backend/Basic-Car-Maintenance` and run `firebase emulators:start`
* Now every request from the app should go against the emulator
* ﻿﻿In the emulator UI at http://127.0.0.1:4000/ you can check if the data you added in the app is added in the emulated Firestore

# Notes
* Anything else that should be noted about how you implemented this feature?

# Screenshot
![SCR-20231031-mvu](https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/20586951/caf290df-fcd8-4aba-9707-e9f539cf1cb9)

2023-11-01 04:01 UTC, mikaelacaron requested changes
Great work!! I haven't tested this because I haven't downloaded everything

> * Make sure Node v 8.0 or higher is installed
> * Make sure Openjdk v 11 or higher is installed (If you installed it via brew, don't forget to add the executable to $PATH, brew will output it as a handy command to execute for you)
> * Make sure firebase-cli is installed (npm install -g firebase-tools)


Can you note the best way to download these? (Preferably with Homebrew) Also I have a few questions, you can comment directly in that thread

2023-11-01 04:01 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/xcshareddata/xcschemes/Basic-Car-Maintenance.xcscheme
> +      </CommandLineArguments>
When would this flag need to be enabled vs disabled? Only when wanting to use the emulator? Otherwise it would be unchecked, which would default to using the real project?

2023-11-01 04:01 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/BasicCarMaintenanceApp.swift
> +        if useEmulator {
Why use UseDefaults, as opposed to the command line argument?

2023-12-01 17:25 UTC, n0rthk1n9 commented on Basic-Car-Maintenance.xcodeproj/xcshareddata/xcschemes/Basic-Car-Maintenance.xcscheme
> +      </CommandLineArguments>
Yes exactly

2023-12-01 17:25 UTC, n0rthk1n9 commented
The best way to install all the requirements is indeed via homebrew:

1. `brew install nvm` (Installs node version manager, so you don't need to update the system node version)
2. `nvm install stable` and `nvm use stable` to download and set the last stable node version
3. `brew install openjdk` to install openjdk. Add the executable to the $PATH via .zshrc or .bashrc file as prompted after installation
4. npm install -g firebase-tools

With that all prerequisites should be installed. Let me know if anything doesn't work

2023-12-01 17:27 UTC, n0rthk1n9 commented on Basic-Car-Maintenance/Shared/BasicCarMaintenanceApp.swift
> +        if useEmulator {
Honestly I don't have a better answer to that question than "Because Peter recommended it doing it like that in his article" But I guess it could also be done via command line arguments, if you prefer that :)

2024-07-30 17:20 UTC, mikaelacaron commented
Thanks so much for all the help on this! I'm finally getting around to implementing it

I'm going to close your PR because I'm working on this on a separate branch, because I'm also updating a few other things.

Your steps were super helpful to finally get this running!

2024-07-30 17:20 UTC, closed without merging