Implemented 'Contributions' Section to SettingsView for GitHub Contributors
mikaelacaron/Basic-Car-Maintenance pull request #27
Opened 2023-10-01 14:23 UTC by Yashraj49

Contributors

# What it Does
* Implements 'Contributions' Section in SettingsView to keep track of contributors to the project.

# How I Tested
* Ran the application.
* Navigated to the SettingsView.
* Observed the new 'Contributions' section.
* Verified that the list of contributors is displayed.
* Tested the functionality of the 'Contributions' section by interacting with it.
* Checked that the GitHub API is fetching and displaying contributors correctly.

2023-10-01 19:14 UTC, mikaelacaron requested changes
Thank you for contributing!

Please go back and follow the instructions in the [README](https://github.com/mikaelacaron/Basic-Car-Maintenance/tree/main#getting-started) about properly setting up the project.
Do not copy everything from the brain marks repo, it is all not needed. The only scope of this issue is adding a new section for the list of contributors.

Once you address one of the comments I've made, mark it as resolved, if you have questions on a specific comment, comment on that thread

If you have any other questions feel free to DM me on [social media](https://mikaelacaron.com/links)

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Dashboard/Views/Contributor.swift
> +    let subscriptionsURL, organizationsURL, reposURL: String
Please put all these properties on separate lines

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Dashboard/Views/Contributor.swift
> +        case nodeID = "node_id"
Because most of these are snake case / camel case, can we use `convertFromSnakeCase` decoding strategy instead? See [these docs](https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase)

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = yashraj.car;
The bundle ID should not change, and the DEVELOPMENT_TEAM should not change in the actual project. Please follow the steps in the [README](https://github.com/mikaelacaron/Basic-Car-Maintenance/tree/main#getting-started) for properly setting up the project

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Info/InfoViewModel.swift
> +class DefaultInfoViewModel: InfoViewModel {
Please give this a different name and remove the protocol it's not needed

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Info/InfoViewModel.swift
> +    }
The scope of #16 does not include adding the version number. Please adjust all the code so that it is not directly copied from the brain marks repo

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Info/InfoView.swift
> +struct InfoView<ViewModel: InfoViewModel>: View {
Use a different name, this is not really specific and doesn't really describe what the view is. Also remove the constraint that the view model needs to be an `InfoViewModel`

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/ViewModels/SettingsViewModel.swift
> +        "vcapilladeveloper"
This is directly copied from brain marks, please customize this for this project. It doesn't make sense to have a list of names from people who have not contributed to this project, and the staticContributors doesn't really make sense to have at all (as a predefined list, if anything you could just include my username and that's it)

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/ViewModels/SettingsViewModel.swift
> +        URLSession.shared.dataTask(with: url) { data, _, error in
Use async await syntax, not closures

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsListView.swift
> +    @StateObject var viewModel: SettingsViewModel
This should be an `@ObservedObject` not a `@StateObject`

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsListView.swift
> +                ForEach(viewModel.staticContributors, id: \.self) { contributor in
Don't use this `staticContributors` if the data is loading, show a `ProgressView()`

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsListView.swift
> +                ForEach(viewModel.contributors!, id: \.self) { contributor in
Make `Contributor` conform to `Identifiable` to remove the `id: \.self` in this ForEach

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/ViewModels/SettingsViewModel.swift
> +        "bugReport": URL(string: "https://github.com/mikaelacaron/Basic-Car-Maintenance/issues")!
Don't include this "bug report" section, this issue is only about showing contributors

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsListView.swift
> +        }
Once you change `getContributors` to use async await, this modifier should be a `.task`

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsListView.swift
> +        .navigationBarHidden(false)
You don't need this, it's `false` by default

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsListView.swift
> +        .navigationBarTitleDisplayMode(.automatic)
You don't need this, it is `.automatic` by default

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsProfileView.swift
> +struct ContributorsProfileViews: View {
This should be singular `ContributorsProfileView`

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsProfileView.swift
> +    var imgUrl: String
These should be `let` not `var`

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsProfileView.swift
> +                case .failure(_):
Instead of `Text("Failed to load image")` show an SF symbol with `person` as the default. Same for the unknown state

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/SettingsView.swift
> +        self._viewModel = StateObject(wrappedValue: SettingsViewModel(authenticationViewModel: authenticationViewModel))
Do not remove the comment about SwiftLint

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/SettingsView.swift
> +    let infoViewModel: InfoViewModel = DefaultInfoViewModel()
This needs to be a state property

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Utilities/Logger+Ext.swift
> +extension Logger {
Why copy this file when it's not used?

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/SettingsView.swift
> +                        if let appVersion = infoViewModel.appVersion {
Adding the app version number is not in the scope of this issue and already is there

2023-10-01 19:14 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/SettingsView.swift
> +            VStack {
Why are you putting everything into a `VStack`?

2023-10-02 18:15 UTC, Yashraj49 commented
hey @mikaelacaron thanks  , for letting me know I will sure look into it

2023-10-03 05:43 UTC, closed without merging

2023-10-03 06:49 UTC, Yashraj49 commented
hey @mikaelacaron I have resolved all conflicts and here i am making a new pull request with updated fork