feature: Use NavigationSplitView rather than TabView for iPad #6
mikaelacaron/Basic-Car-Maintenance pull request #279
Opened 2023-12-18 08:07 UTC by windrunner21

# What it Does
* Closes #6 
* I have added `NavigationSplitView` logic into `MainTabView` struct. This addition is mutating only iPad version right now (completely works) and should affect MacOS version as well in the future (MacOS isn't building as of now). iPhone proceeds with `TabView` navigation. I have also refactored the code - added extension to hold `@ViewBuilder` views for better reusability and more readable code - because at the end of the day `TabView` and `NavigationSplitView` use the same content.

# How I Tested
* I have tested this new feature on Previews first and later on Simulators.
* Tested on iPhone 15 Pro Max - 17.0.1
* Tested on iPad Pro 12.9 inch - 17.0.1
* iPad shows `NavigationSplitView` navigation - can be toggled to be shown/hidden.
* iPhone shows `TabView` navigation.

# Notes
* There is a comment I have left in the code that TabSelection enum can be changed to conform to String rather than Int. If needed can be easily swiped out, currently is left as is.

# Screenshot
* Two screen recordings - iPad and iPhone.

https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/18750749/7eda95ac-3913-426c-b3a7-eb210ba943b9

https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/18750749/d78bad15-0f16-486e-bf8c-3a3612f3d982

2023-12-25 11:21 UTC, windrunner21 commented
@mikaelacaron hi, hope all is well 😄 did you have the chance to look at the PR?

2023-12-25 13:32 UTC, mikaelacaron commented
@windrunner21 No I haven't, and it's the holidays so I'm not going to be looking at this today. You'll see my review when I have time

2023-12-25 15:04 UTC, windrunner21 commented
@mikaelacaron oh sorry, you are right, I totally forgot about it. Merry Christmas! Have a great holiday 🥳

2023-12-31 06:07 UTC, mikaelacaron requested changes
Great work!! I have several suggestions and a few things to fix.

Also can you order the functions `navigationSplitView`, `tabView`, and then `selectionContent`

There's also a bug, the tab view is saved when you close the app and open it again (for iPhone), it remembers which tab you were on, I'd like that same functionality for the navigation split view

2023-12-31 06:07 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +    private func navigationSplitView() -> some View {
```suggestion
    /// Primarily used on iPad and Mac devices
    /// - Returns: `NavigationSplitView`
    @ViewBuilder
    private func navigationSplitView() -> some View {
```

Changing the formatting of the documentation comment

2023-12-31 06:07 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +    @ViewBuilder func tabView() -> some View {
```suggestion
    /// Primarily used on iPhone devices
    /// - Returns: `TabView` navigation
    @ViewBuilder func tabView() -> some View {
```

Changing the formatting of the documentation comment

2023-12-31 06:07 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +    @State private var selectedTabId: TabSelection.ID? = .dashboard
Should this be type `TabSelection.ID?` or `TabSelection.id?`

2023-12-31 06:07 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +    var label: String {
This should be type `LocalizedStringKey`, for these values to be localized

2023-12-31 06:07 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +            .navigationTitle("Sidebar")
Instead of this saying `Sidebar`, can this say `Basic Car`

2023-12-31 06:07 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +    }
Please remove this function, I don't really see a ton of value in it, because it's a one line function replacing a call that still is only one line

2023-12-31 06:07 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +extension MainTabView {
I think just keep everything in the MainTabView, I don't really see a need for an extension, because it's all still in the same file anyways

2023-12-31 06:07 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +    private func splitViewDetailContent() -> some View {
Can you actually put the content of this function in the `detail` closure and remove this function. I find it harder to read what's happening, because it's split out of the `NavigationSplitView`'s initializer

And with that, the `else` block isn't needed

2023-12-31 06:07 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +#if os(iOS)
Can you indent all the compiler directives with the code rather than having them all the way to the left?

```swift
Group {
    #if os(iOS)
    if UIDevice.current.userInterfaceIdiom == .pad {
        navigationSplitView()
    } else {
        tabView()
    }
    #else
    navigationSplitView()
    #endif
}
```

2024-01-04 20:57 UTC, windrunner21 commented
hey @mikaelacaron, sorry for the late reply, still on holidays! I'll update PR with requested changes by Sunday latest.

2024-01-05 00:52 UTC, mikaelacaron commented
@windrunner21 No worries at all! Take vacation! 👍

2024-01-06 20:05 UTC, mikaelacaron commented
@windrunner21  After you address all the comments, please click the re-review button

<img width="345" alt="Re-review button" src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/22946902/ad72ef8c-4889-4d07-814b-f0d3640eb883">

Also if you fix something I mentioned and don't have any questions, go ahead and click the Resolve button, but if you have a question, you can comment on that question directly

2024-01-06 20:11 UTC, windrunner21 commented
@mikaelacaron I didn't click it yet because I still have to solve the bug with reopening the same tab after relaunching application. I wanted to solve everything and then request review 😄

2024-01-06 20:13 UTC, mikaelacaron commented
Yup! You should resolve everything for sure! I just mentioned this cause I got notified you were working on it haha

And I saw that I didn't mention it in my first review

2024-01-06 20:40 UTC, windrunner21 commented on Basic-Car-Maintenance/Shared/MainView/Views/MainTabView.swift
> +    @State private var selectedTabId: TabSelection.ID? = .dashboard
This should be `TabSelection.ID` as it's (`.ID`) inherited from `Identifiable` protocol.

2024-01-07 07:10 UTC, windrunner21 commented
@mikaelacaron just finished with the bug fix, implemented it in such a way that `TabView` / `NavigationSplitView` are having the same last opened tab.

2024-07-08 21:55 UTC, merged

2024-07-08 21:55 UTC, mikaelacaron commented
@windrunner21 thanks for working on this! haha just now finally getting around to finishing up the final bits of this project to launch it