Issue 305 - Create Dark and Tinted Icons for the App
mikaelacaron/Basic-Car-Maintenance pull request #319
Opened 2024-10-03 04:45 UTC by rajhraval

# What it Does
* Closes #305 
* The app supports dark mode and tinted app icons.

# How I Tested
* Run the app after following the instructions in [Contributing.md](https://github.com/mikaelacaron/Basic-Car-Maintenance/blob/dev/CONTRIBUTING.md#start-here)
* Go To Settings -> Change App Icon -> Pick an app icon
* Close the App -> Tap and Hold on the Home Screen -> Click on Edit and then on Customise
* Select Light To Test The Light Mode App Icon Variant
* Select Dark To Test the Dark Mode App Icon Variant
* Select Tinted to Test the Tinted App Icon Variant

# Notes
* In the Change App Icon View, the icons are not visible, this is not correct as user doesn't how the app icon looks like before the user applies it.

# Screenshot

https://github.com/user-attachments/assets/408942ce-4673-4779-808a-ae99f35d51e3

2024-10-04 14:20 UTC, mikaelacaron requested changes
I tried to tap on the red car, still in light mode, and it failed with
`Updating icon to Optional("AppIcon-car-red") failed.`
actually they're all failing right now
```
Updating icon to Optional("AppIcon-car-dark") failed.
Updating icon to Optional("AppIcon-car-red") failed.
Updating icon to Optional("AppIcon-car-yellow") failed.
Updating icon to Optional("AppIcon-car-black") failed.
Updating icon to Optional("AppIcon-car-orange") failed.
Updating icon to Optional("AppIcon-car-yellow") failed.
Updating icon to Optional("AppIcon-car-black") failed.
Updating icon to Optional("AppIcon-car-orange") failed.
```

AppIcon-Car-Dark "dark version" of this doesn't have an icon, should it?

2024-10-04 14:20 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = SJ64B32FPH;
Don't commit this! look back at the [contributing guidelines](https://github.com/mikaelacaron/Basic-Car-Maintenance/blob/dev/CONTRIBUTING.md#start-here) with the xccconfig file steps

it looks like you changed the development team in the project, which you shouldn't do

2024-10-04 14:20 UTC, mikaelacaron commented on Basic-Car-Maintenance/Assets.xcassets/AppIcon-Car-Orange.appiconset/Tinted.png
Do we actually need tinted versions of all the colored cars? cause in reality they'll all be the same? so can we just use one asset for the tinted color versions?

2024-10-04 14:21 UTC, mikaelacaron commented
Once you fix everything, please click the re-review button

<img width="345" alt="Re-review button" src="https://github.com/user-attachments/assets/f455ba01-806c-48c4-8d72-b265044daf34">

2024-10-04 14:48 UTC, rajhraval commented on Basic-Car-Maintenance/Assets.xcassets/AppIcon-Car-Orange.appiconset/Tinted.png
Sure, will fix this.

2024-10-04 15:31 UTC, rajhraval commented
> I tried to tap on the red car, still in light mode, and it failed with `Updating icon to Optional("AppIcon-car-red") failed.` actually they're all failing right now
> 
> ```
> Updating icon to Optional("AppIcon-car-dark") failed.
> Updating icon to Optional("AppIcon-car-red") failed.
> Updating icon to Optional("AppIcon-car-yellow") failed.
> Updating icon to Optional("AppIcon-car-black") failed.
> Updating icon to Optional("AppIcon-car-orange") failed.
> Updating icon to Optional("AppIcon-car-yellow") failed.
> Updating icon to Optional("AppIcon-car-black") failed.
> Updating icon to Optional("AppIcon-car-orange") failed.
> ```
> 
> AppIcon-Car-Dark "dark version" of this doesn't have an icon, should it?

This is weird, it's working fine for me while running simulator.
For AppIcon-Car-Dark, it's already dark should it doesn't require, actually I feel it's redundant.
Because AppIcon-Car-Black's dark variant is the AppIcon-Car-Dark icon itself.

2024-10-04 15:43 UTC, mikaelacaron commented
> For AppIcon-Car-Dark, it's already dark should it doesn't require, actually I feel it's redundant.

I agree, let's just remove it now, cause that was made pre-iOS 18

Do the icons show on the ChooseAppIconView for you? They still weren't showing for me

The errors can also mean the files aren't properly added to the project? And target membership?

2024-10-04 16:02 UTC, rajhraval commented
> I agree, let's just remove it now, cause that was made pre-iOS 18

Cool will remove the AppIconDark

> Do the icons show on the ChooseAppIconView for you? They still weren't showing for me

No they don't because there are no images present for those icons, we need to have separate images created for them so UIImage(named: ) returns value currently they return a UIImage() (Empty Value)

> The errors can also mean the files aren't properly added to the project? And target membership?
You are running in Simulator correct and iOS 18 right?, the files are added and target is also just fine.

<img width="880" alt="image" src="https://github.com/user-attachments/assets/c42d7dd9-be15-43af-8242-bcc5e0238cb1">

2024-10-04 16:02 UTC, mikaelacaron commented
comment whenever that is done please! cause you can't click re-review again haha

2024-10-05 04:26 UTC, rajhraval commented
Done @mikaelacaron, regarding the errors, I still can't reproduce them.

2024-10-05 17:04 UTC, mikaelacaron requested changes
I figured out why there's an error, see comments below! also for me the icons aren't showing on the `ChooseAppIconView`, but if you are seeing them, let me know.
don't fix it, we can make a new issue for this

2024-10-05 17:04 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Models/AppIcon.swift
>      case carRed = "AppIcon-car-red"
I'm surprised you aren't getting any errors
From this screenshot of the name of the assets, vs what's in this file. The assets has capital letters, and the names in this file use lowercase letters

I checked and this is the reason for the error. Can you please fix it so that they're consistent between the file names and these enum raw values
![Screenshot 2024-10-05 at 5 46 10 PM](https://github.com/user-attachments/assets/c801d959-066d-4fab-ac76-c3be6fd3a8be)

2024-10-05 17:04 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = SJ64B32FPH;
This still needs to be resolve dplease!

2024-10-05 17:08 UTC, mikaelacaron commented on Basic-Car-Maintenance/Assets.xcassets/AppIcon-Car-Orange.appiconset/Tinted.png
Nevermind! Kinda irrelevant
I meant do we need multiple of the same asset for all the tinted icons? Or can we use the same asset for all of the colors? seeing Figam, it looks like it's the same, but I couldn't tell just looking at the git diff

(we can resolve this thread)

2024-10-06 05:24 UTC, rajhraval commented on Basic-Car-Maintenance/Shared/Models/AppIcon.swift
>      case carRed = "AppIcon-car-red"
<img width="224" alt="image" src="https://github.com/user-attachments/assets/41b009aa-2773-47f1-b35a-b998380ebd34">
 
I have already changed this, have you pulled the latest changes😅

2024-10-06 05:26 UTC, rajhraval commented
All done.

2024-10-08 01:25 UTC, rajhraval commented
Any update @mikaelacaron

2024-10-08 14:14 UTC, mikaelacaron approved these changes
Great work!! the development team was removed and not properly set (see the contributing.md file about how to set this up properly. I'll fix it manually for this PR

also note I have multiple days to review PRs, there's many things to mange, and I may not get to every PR within 24 hours

2024-10-08 14:14 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
>  				GENERATE_INFOPLIST_FILE = YES;
```suggestion
				DEAD_CODE_STRIPPING = YES;
				DEVELOPMENT_ASSET_PATHS = "\"Basic-Car-Maintenance/Preview Content\"";
				ENABLE_HARDENED_RUNTIME = YES;
				ENABLE_PREVIEWS = YES;
				GENERATE_INFOPLIST_FILE = YES;
```

This should be fully removed, as opposed to be set to empty

2024-10-08 14:14 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
>  				ENABLE_PREVIEWS = YES;
```suggestion
				DEVELOPMENT_ASSET_PATHS = "\"Basic-Car-Maintenance/Preview Content\"";
				ENABLE_HARDENED_RUNTIME = YES;
				ENABLE_PREVIEWS = YES;
```
removed

2024-10-08 14:16 UTC, merged