Build All Previews and Updated with @Previewable
mikaelacaron/Basic-Car-Maintenance pull request #323
Opened 2024-10-04 05:35 UTC by Yashraj49

# What it Does
* Closes #309 
* Updated all previews with @Previewable macro wherever needed

# How I Tested
* Played the Canvas in SwiftUI to confirm previews are working as expected

2024-10-04 05:42 UTC, Yashraj49 commented
Hey @mikaelacaron,

I’ve addressed the issue as requested. Here are the changes:

	•	Updated all previews to use the @Previewable macro where necessary.
	•	Removed FirebaseFirestoreSwift since it’s deprecated by Firebase.

Feel free to review the updates, and let me know if any adjustments are needed.

2024-10-04 14:03 UTC, mikaelacaron requested changes
I have several comments that need resolved please. If you have any questions, you can comment directly on that thread, otherwise click the resolve button once you've addressed my comment. Once you fix everything, please click the re-review button

Notice also how it's now that this PR isn't accurate because of removing Firebase stuff, that's not noted in the PR title or what this issue was about. Mixing multiple things in PRs makes it harder to tell the history over time.

Remove all the firebase related changes and redo the Previewable changes please (this may be easier to just make a new branch and PR, otherwise you'll get lots of changes cause Xcode moves things around.

Also make a new issue about this deprecation and where it's documented

<img width="345" alt="Re-review button" src="https://github.com/user-attachments/assets/e2cb0f05-6207-46a2-acc7-79202bd049e2">

2024-10-04 14:03 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> -		FF4E82C22AD39863004949AF /* FirebaseStorage in Frameworks */ = {isa = PBXBuildFile; productRef = FF4E82C12AD39863004949AF /* FirebaseStorage */; };
Don't do this in this PR, can you create a separate issue and PR for why this is necessary?
Several packages are remove and I'm unsure why

2024-10-04 14:03 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				minimumVersion = 11.3.0;
also don't update packages, this is something that should explicitly be in it's own PR, not mixed with other things

again, make a new issue / PR for this (but just make an issue, this is something that someone else can do as well to contribute to the project

2024-10-04 14:03 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Models/OdometerReading.swift
> +import FirebaseFirestore
Please put all the packages back to the way they were and then I can review the rest of the files

2024-10-04 14:25 UTC, Yashraj49 commented
ok @mikaelacaron I got it thanks , so  can I just edit the current project.pbxproj as it was before , sure I will but this packages back also , I didn't get    "redo the Previewable changes please" like if is there something wrong in this change for @Previewable ?

2024-10-04 15:25 UTC, mikaelacaron commented
> I didn't get "redo the Previewable changes please" like if is there something wrong in this change for @Previewable ?

I didn't read them because there was too much going on with all the package stuff

Yes you could change the pbxproj file manually, but it would be faster and easier to just branch from `dev` again, and then redo your changes

2024-10-05 06:20 UTC, Yashraj49 commented
> > I didn't get "redo the Previewable changes please" like if is there something wrong in this change for @Previewable ?
> 
> I didn't read them because there was too much going on with all the package stuff
> 
> Yes you could change the pbxproj file manually, but it would be faster and easier to just branch from `dev` again, and then redo your changes

oh ok got it , so should I create new PR ? if so then I will close this current PR

2024-10-05 12:31 UTC, mikaelacaron commented
@Yashraj49 Yes, I think it will be easiest to close this PR and create a new one

create a new branch from `dev` and then do your Previewable changes

and make an issue about what's deprecated, link to the docs, and why we need to change it

2024-10-05 13:13 UTC, closed without merging