#16 view GitHub contributors(new)
mikaelacaron/Basic-Car-Maintenance pull request #68
Opened 2023-10-04 13:57 UTC by Yashraj49

Contributors

# What it Does
* Implements 'Contributions' Section in SettingsView to keep track of contributors to the project.
* Closes #16 

# How I Tested
* Ran the application.
* Navigated to the SettingsView.
* Observed the new 'Contributions' section.
* Verified that the list of contributors is displayed.
* Tested the functionality of the 'Contributions' section by interacting with it.
* Checked that the GitHub API is fetching and displaying contributors correctly.

# Notes
* I haven't included my team ID, as I have not yet enrolled in Apple Dev Program

# Screenshots 
<div style="display: flex; flex-direction: row;">

<div>
  <img src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/88454884/e177d96f-1b48-4321-b105-1e46a4c90b9d" alt="Simulator Screenshot - iPhone 15 Pro - 2023-10-04 at 19 19 48" width="300" />
  
  <img src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/88454884/937e7d91-e161-45b6-bf3b-bdef8ca1d63c" alt="Simulator Screenshot - iPhone 15 Pro Max" width="300" />
</div>

2023-10-04 13:57 UTC, Yashraj49 commented
@mikaelacaron  I have fixed the required conflicts you may review it

2023-10-04 14:00 UTC, mikaelacaron requested changes
It looks like the `xcconfig` is still moved in the project

2023-10-04 14:00 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
You can see here something is still happening with the `xcconfig` file moving around, can you make sure this is set up correctly and doesn't move? Thanks! If you have any issues DM me on social media

2023-10-04 14:49 UTC, Yashraj49 commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
I didn't moved it . also I have no idea how to move it what is needed to be done here I mean is there any way to set it back ??  I

2023-10-04 15:29 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
When you cloned the repo for the first time, did you run the terminal command to copy the file, or did you do File > New in Xcode to make the `xcconfig`?

2023-10-04 15:43 UTC, Yashraj49 commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
yes I did ,at the very first I did ran that command using terminal to its directory and then that file was created there

2023-10-04 15:59 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
If you ran the command the then the xcconfig shouldn't have changed at all, in the pbxproj file
Can you try to just clone the `dev` branch again (just in a different place than you've been working in) and run the command again, and see if the pbxproj file has changed?

2023-10-04 16:11 UTC, Yashraj49 commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
I will sure do that but how's that going to help in now getting the file as before it was ??

2023-10-04 16:15 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
1st it confirms whether that is how it works, and 2nd, you can copy code from your PR over to that branch, if it works correctly (if you want), or the other solution is properly resolving the current merge conflicts

2023-10-04 16:43 UTC, Yashraj49 commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
ok that's fine and how can I properly resolve the current merge conflict ??

2023-10-04 17:03 UTC, mikaelacaron commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
Look into git tutorials and how to solve merge conflicts!

2023-10-04 17:22 UTC, Yashraj49 commented on Basic-Car-Maintenance.xcodeproj/project.pbxproj
> +				E5C46DD72ACD2D4B0098D448 /* Basic-Car-Maintenance.xcconfig in Resources */,
hey I have cloned dev branch again also I noticed that bundle id section is empty so should I let remain like that or should I paste your bundle id over there

2023-10-05 01:58 UTC, mikaelacaron commented
Replaced by #70

2023-10-05 01:58 UTC, closed without merging