fixed recent conflict
mikaelacaron/Basic-Car-Maintenance pull request #70
Opened 2023-10-04 18:11 UTC by Yashraj49

Contributors

# What it Does
* Implements 'Contributions' Section in SettingsView to keep track of contributors to the project.
* Closes #16 

# How I Tested
* Ran the application.
* Navigated to the SettingsView.
* Observed the new 'Contributions' section.
* Verified that the list of contributors is displayed.
* Tested the functionality of the 'Contributions' section by interacting with it.
* Checked that the GitHub API is fetching and displaying contributors correctly.

# Notes
* I haven't included my team ID, as I have not yet enrolled in Apple Dev Program

# Screenshots 
<div style="display: flex; flex-direction: row;">

<div>
  <img src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/88454884/e177d96f-1b48-4321-b105-1e46a4c90b9d" alt="Simulator Screenshot - iPhone 15 Pro - 2023-10-04 at 19 19 48" width="300" />
  
  <img src="https://github.com/mikaelacaron/Basic-Car-Maintenance/assets/88454884/937e7d91-e161-45b6-bf3b-bdef8ca1d63c" alt="Simulator Screenshot - iPhone 15 Pro Max" width="300" />
</div>

2023-10-04 18:11 UTC, Yashraj49 commented
@mikaelacaron I have done as suggested here goes a fixed Pr

2023-10-04 18:52 UTC, mikaelacaron commented
@Yashraj49 Does this replace PR #68? if so can you please close that other PR

2023-10-05 02:12 UTC, mikaelacaron requested changes
This is just about ready to merge! Thanks for all your work on it!
I made several comments that aren't critical, but just notes.

The important thing that I want to know before merging this, is the `xcstrings` file there's several changes that I wouldn't expect I wouldn't expect there to be any changes to anything except adding one new string `Contributors`
Do you know what happened here?

2023-10-05 02:12 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Models/Contributor.swift
> +    let receivedEventsURL: String
I don't think we actually need all of these properties, because they're not being used

2023-10-05 02:12 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Localizable.xcstrings
I want to merge this, but this file is one that I'm worried about. I wouldn't expect any of these values to have changed (with the scope of your task), did you have to resolve a merge conflict here?

2023-10-05 02:12 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Settings/Views/ContributorsProfileView.swift
> +    }
Because this is a struct, you shouldn't need an `init`

2023-10-05 02:44 UTC, mikaelacaron commented on Basic-Car-Maintenance/Shared/Localizable.xcstrings
I just aw this in another PR, it must just be how the Localizable.xcstrings file works and moves stuff around

2023-10-05 02:45 UTC, merged